apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow-controller
spec:
  template:
    spec:
      containers:
        - name: workflow-controller
          image: registry.cn-zhangjiakou.aliyuncs.com/kubeflow-zhentian/workflow-controller:v3.1.6-patch-license-compliance
          args:
            - --configmap
            - workflow-controller-configmap
            - --executor-image
            - registry.cn-zhangjiakou.aliyuncs.com/kubeflow-zhentian/argoexec:v3.1.6-patch-license-compliance
          resources:
            requests:
              cpu: 100m
              memory: 500Mi
