apiVersion: batch/v1
kind: Job
metadata:
  generateName: storage-version-migration-serving-
  namespace: knative-serving
  labels:
    app: "storage-version-migration-serving"
    serving.knative.dev/release: "v0.22.1"
  name: storage-version-migration-serving
spec:
  ttlSecondsAfterFinished: 600
  backoffLimit: 10
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: "storage-version-migration-serving"
    spec:
      serviceAccountName: controller
      restartPolicy: OnFailure
      containers:
        - name: migrate
          image: registry.cn-zhangjiakou.aliyuncs.com/kubeflow-zhentian/serving-post-install-jobs-migrate:1.0
          args:
            - "services.serving.knative.dev"
            - "configurations.serving.knative.dev"
            - "revisions.serving.knative.dev"
            - "routes.serving.knative.dev"
